name: alex_super_app_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - apps/circle_of_fifths_app
  - apps/quiz_app
  - apps/super_app
  - modules/circle_of_fifths
  - modules/quiz
  - modules/string_tension_calculator
  - packages/core/app_theme
  - packages/core/module_contracts
  - packages/core/scoped_di
  - tools/alex_workspace_lints
